job_type: train_self_supervised
workspace_path: C:/workspace/tgn-workspace
training:
  device: cpu
  num_epoch: 10
  backprop_every: 10
  train_batch_size: 128
  eval_batch_size: 128
  evaluation_seed: 1024
