job_type: train_supervised
workspace_path: /home/huoranli/tgn-workspace
data:
  uniform: False
  randomize_features: False
training:
  device: cpu
  num_epoch: 100
  backprop_every: 1
  early_stop: 3
  train_batch_size: 100
  eval_batch_size: 200
  learning_rate: 0.0003
  embedding_model_version: night_self_supervised
